# Generated by Django 4.2.27 on 2025-12-07 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultsapp', '0003_carousel_contact_us_our_partners_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='location',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact_us',
            name='message',
            field=models.CharField(max_length=1000),
        ),
    ]
