# Generated by Django 4.2.27 on 2025-12-07 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultsapp', '0004_school_location_alter_contact_us_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='school_logo',
            field=models.FileField(default=0, upload_to='pics'),
            preserve_default=False,
        ),
    ]
