# Generated by Django 4.2.27 on 2025-12-07 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultsapp', '0005_school_school_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='police_station',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
