# Generated by Django 4.2.27 on 2025-12-07 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultsapp', '0006_school_police_station'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='head_teacher_name',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
