# Generated by Django 4.2.27 on 2025-12-07 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultsapp', '0007_school_head_teacher_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='dos_theology_name',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
